name: Daily Build
# build and tweet
on:
  workflow_dispatch:
  schedule:
    - cron:  '13 11 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - uses: actions/cache@v2
      name: Configure pip caching
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Install Python dependencies
      run: |
        python -m pip install -r requirements.txt
    - name: Processing
      env:
          city_code: ${{ secrets.CITY_CODE }}
      run: |-
        python 'python/foodbank.py'
        python 'python/update_readme.py'
    - name: Commit and push if changed
      run: |-
        git diff
        git config --global user.email "foodbank-bot@example.com"
        git config --global user.name "foodbank-bot"
        git diff --quiet || (git add -A && git commit -m "Updated data")
        git push
