---
name: Scheduled Build

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    - name: Check out repo
      uses: actions/checkout@v4.1.1
      with:
        fetch-depth: 0
   
    - name: Download Feed
      run: |-
        curl "https://www.givefood.org.uk/api/2/foodbank/cheltenham/" | jq . > foodbank.json
        
    - name: Commit and push changes
      run: |-
        git config user.name "GitHub Action"
        git config user.email "action@github.com"
        git diff --quiet || (git add -A && git commit -m "Updated `date +'%Y-%m-%d %H:%M:%S'`")
        git push
        
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.8
        
    - uses: actions/cache@v4
      name: Configure pip caching
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          
    - name: Install Python dependencies
      run: python -m pip install -r requirements.txt
      
    - name: Processing
      run: python 'python/update_readme.py'
      
    - name: Commit and push
      run: |-
        git config user.name "GitHub Action"
        git config user.email "action@github.com"
        git diff --quiet || (git add -A && git commit -m "Updated `date +'%Y-%m-%d %H:%M:%S'`")
        git push
